import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import GroupMatchesSection from '../components/matches/GroupMatchesSection';
import PlayoffSection from '../components/matches/PlayoffSection';
import './TournamentDetail.css';

function TournamentDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [tournament, setTournament] = useState(null);
  const [players, setPlayers] = useState([]);
  const [matches, setMatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [newPlayerName, setNewPlayerName] = useState('');
  const [notification, setNotification] = useState({ message: '', type: '' });
  const [activeTab, setActiveTab] = useState('prehled'); // prehled | hraci | zapasy
  const [standings, setStandings] = useState(null);
  const [editingMatchId, setEditingMatchId] = useState(null);
  const [editingScore, setEditingScore] = useState('');

  useEffect(() => {
    fetchTournament();
    fetchPlayers();
    fetchMatches();
    fetchStandings();
  }, [id]);

  const fetchTournament = async () => {
    try {
      const response = await fetch(`http://localhost:3000/api/tournaments/${id}`);
      if (response.ok) {
        const data = await response.json();
        setTournament(data);
      } else {
        setError('Turnaj nebyl nalezen');
      }
    } catch (error) {
      console.error('Error fetching tournament:', error);
      setError('Chyba při načítání turnaje');
    } finally {
      setLoading(false);
    }
  };

  const fetchPlayers = async () => {
    try {
      const response = await fetch(`http://localhost:3000/api/tournaments/${id}/players`);
      if (response.ok) {
        const data = await response.json();
        setPlayers(data);
      }
    } catch (error) {
      console.error('Error fetching players:', error);
    }
  };

  const fetchMatches = async () => {
    try {
      const response = await fetch(`http://localhost:3000/api/tournaments/${id}/matches`);
      if (response.ok) {
        const data = await response.json();
        setMatches(data);
      }
    } catch (error) {
      console.error('Error fetching matches:', error);
    }
  };

  const fetchStandings = async () => {
    try {
      const response = await fetch(`http://localhost:3000/api/tournaments/${id}/standings`);
      if (response.ok) {
        const data = await response.json();
        setStandings(data);
      }
    } catch (error) {
      console.error('Error fetching standings:', error);
    }
  };

  const handleStartTournament = async () => {
    if (players.length < 2) {
      setNotification({ message: 'Turnaj musí mít alespoň 2 hráče', type: 'error' });
      return;
    }

    if (!window.confirm('Opravdu chcete zahájit turnaj? Po zahájení nelze přidávat nebo odebírat hráče.')) {
      return;
    }

    try {
      const response = await fetch(`http://localhost:3000/api/tournaments/${id}/start`, {
        method: 'POST'
      });

      if (response.ok) {
        const data = await response.json();
        setNotification({ message: `Turnaj byl zahájen! Vygenerováno ${data.matchesGenerated} zápasů.`, type: 'success' });
        
        // Refresh tournament and matches
        await fetchTournament();
        await fetchMatches();
        await fetchStandings();
        
        setTimeout(() => setNotification({ message: '', type: '' }), 5000);
      } else {
        const error = await response.json();
        setNotification({ message: error.error || 'Chyba při zahájení turnaje', type: 'error' });
      }
    } catch (error) {
      console.error('Error starting tournament:', error);
      setNotification({ message: 'Chyba při spojení se serverem', type: 'error' });
    }
  };

  const saveMatchResult = async (matchId, scoreStr) => {
    const [a,b] = scoreStr.split(':').map(n=>parseInt(n,10));
    try {
      const resp = await fetch(`http://localhost:3000/api/matches/${matchId}/result`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ player1_score: a, player2_score: b })
      });
      if (resp.ok) {
        const data = await resp.json();
        await fetchMatches();
        await fetchStandings();
        
        // Check if next playoff round was auto-generated
        if (data.autoGeneratedNextRound) {
          setNotification({ message: 'Výsledek uložen a další kolo play-off automaticky vygenerováno!', type: 'success' });
        } else {
          setNotification({ message: 'Výsledek byl uložen', type: 'success' });
        }
        
        setTimeout(()=>setNotification({ message:'', type:'' }), 3000);
        setEditingMatchId(null);
        setEditingScore('');
      } else {
        const err = await resp.json();
        setNotification({ message: err.error || 'Chyba při ukládání výsledku', type: 'error' });
      }
    } catch (e) {
      console.error(e);
      setNotification({ message: 'Chyba při spojení se serverem', type: 'error' });
    }
  };

  const resetMatchResult = async (matchId) => {
    try {
      const resp = await fetch(`http://localhost:3000/api/matches/${matchId}/reset`, {
        method: 'PUT'
      });
      if (resp.ok) {
        await fetchMatches();
        await fetchStandings();
        setNotification({ message: 'Výsledek byl resetován', type: 'success' });
        setTimeout(()=>setNotification({ message:'', type:'' }), 3000);
        setEditingMatchId(null);
        setEditingScore('');
      } else {
        const err = await resp.json();
        setNotification({ message: err.error || 'Chyba při resetování výsledku', type: 'error' });
      }
    } catch (e) {
      console.error(e);
      setNotification({ message: 'Chyba při spojení se serverem', type: 'error' });
    }
  };

  const handleMatchStateUpdate = async (matchId, payload, successMessage) => {
    try {
      const resp = await fetch(`http://localhost:3000/api/matches/${matchId}/state`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (resp.ok) {
        await fetchMatches();
        setNotification({ message: successMessage || 'Stav zápasu aktualizován', type: 'success' });
        setTimeout(()=>setNotification({ message:'', type:'' }), 2500);
      } else {
        const err = await resp.json();
        setNotification({ message: err.error || 'Chyba při změně stavu zápasu', type: 'error' });
      }
    } catch (e) {
      console.error(e);
      setNotification({ message: 'Chyba při spojení se serverem', type: 'error' });
    }
  };

  const getTableOptions = () => {
    const count = tournament?.pocetStolu || 1;
    return Array.from({ length: count }, (_, i) => i + 1);
  };

  const handleAddPlayer = async (e) => {
    e.preventDefault();
    
    if (!newPlayerName.trim()) {
      setNotification({ message: 'Prosím zadejte jméno hráče', type: 'error' });
      return;
    }

    try {
      const response = await fetch(`http://localhost:3000/api/tournaments/${id}/players`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jmeno: newPlayerName })
      });

      if (response.ok) {
        const newPlayer = await response.json();
        setPlayers([...players, newPlayer]);
        setNewPlayerName('');
        setNotification({ message: 'Hráč byl úspěšně přidán', type: 'success' });
        setTimeout(() => setNotification({ message: '', type: '' }), 3000);
      } else {
        const error = await response.json();
        setNotification({ message: error.error || 'Chyba při přidávání hráče', type: 'error' });
      }
    } catch (error) {
      console.error('Error adding player:', error);
      setNotification({ message: 'Chyba při spojení se serverem', type: 'error' });
    }
  };

  const handleDeletePlayer = async (playerId) => {
    if (!window.confirm('Opravdu chcete odstranit tohoto hráče?')) {
      return;
    }

    try {
      const response = await fetch(`http://localhost:3000/api/players/${playerId}`, {
        method: 'DELETE'
      });

      if (response.ok) {
        setPlayers(players.filter(p => p.id !== playerId));
        setNotification({ message: 'Hráč byl úspěšně odstraněn', type: 'success' });
        setTimeout(() => setNotification({ message: '', type: '' }), 3000);
      } else {
        setNotification({ message: 'Chyba při mazání hráče', type: 'error' });
      }
    } catch (error) {
      console.error('Error deleting player:', error);
      setNotification({ message: 'Chyba při spojení se serverem', type: 'error' });
    }
  };

  const getMatchesByRound = (matches) => {
    // For mixed tournaments, group all group-stage matches by round number across all groups
    if (tournament?.typ === 'smiseny') {
      const groupsByRound = new Map();
      const playoffs = [];

      matches.forEach(m => {
        if (m.round >= 900) {
          playoffs.push(m);
        } else {
          const roundInGroup = m.round % 100 || 0;
          if (!groupsByRound.has(roundInGroup)) groupsByRound.set(roundInGroup, []);
          groupsByRound.get(roundInGroup).push(m);
        }
      });

      const arr = Array.from(groupsByRound.entries())
        .map(([round, roundMatches]) => ({ round, roundMatches }))
        .sort((a,b)=> a.round - b.round);

      if (playoffs.length) {
        arr.push({ round: 900, roundMatches: playoffs });
      }
      return arr;
    }

    // Default grouping by exact round
    const roundsMap = new Map();
    matches.forEach(match => {
      if (!roundsMap.has(match.round)) {
        roundsMap.set(match.round, []);
      }
      roundsMap.get(match.round).push(match);
    });
    return Array.from(roundsMap.entries())
      .map(([round, roundMatches]) => ({ round, roundMatches }))
      .sort((a, b) => a.round - b.round);
  };

  const getRoundLabel = (round, typ) => {
    if (typ === 'smiseny') {
      if (round >= 900) return 'Play-off';
      // In our UI we group group-stage across groups by round number
      if (round < 100) return `Kolo ${round}`;
      const groupNum = Math.floor(round / 100);
      const roundNum = round % 100;
      return `Skupina ${groupNum}, Kolo ${roundNum}`;
    }
    // pavouk & skupina
    return `Kolo ${round}`;
  };

  const getPlayoffRoundName = (matchNumber, totalMatchesInRound) => {
    // Determine playoff stage based on number of matches
    // 1 match = Final, 2 = Semifinal, 4 = Quarterfinal, 8 = Round of 16, etc.
    if (totalMatchesInRound === 1) return 'Finále';
    if (totalMatchesInRound === 2) return 'Semifinále';
    if (totalMatchesInRound === 4) return 'Čtvrtfinále';
    if (totalMatchesInRound === 8) return 'Osmifinále';
    if (totalMatchesInRound === 16) return 'Šestnáctifinále';
    return `Kolo ${Math.ceil(Math.log2(totalMatchesInRound)) + 1}`;
  };

  const getTypLabel = (typ) => {
    const typy = {
      'pavouk': 'Pavouk (Vyřazovací systém)',
      'skupina': 'Skupinový systém',
      'smiseny': 'Smíšený (Skupiny + Pavouk)'
    };
    return typy[typ] || typ;
  };

  const getStatusLabel = (status) => {
    const statusy = {
      'nadchazejici': 'Nadcházející',
      'probiha': 'Probíhá',
      'ukonceny': 'Ukončený',
      'nehrany': 'Nehrán'
    };
    return statusy[status] || status;
  };

  const renderStandingsTable = (rows) => {
    if (!rows || rows.length === 0) return (
      <div className="empty-players"><p>Zatím nejsou k dispozici žádná data pro tabulku</p></div>
    );
    return (
      <table className="standings-table">
        <thead>
          <tr>
            <th>Poř.</th>
            <th>Hráč</th>
            <th>Zápasy</th>
            <th>Výhry</th>
            <th>Prohry</th>
            <th>Sety</th>
            <th>Rozdíl</th>
          </tr>
        </thead>
        <tbody>
          {rows.map(r => (
            <tr key={r.player_id}>
              <td>{r.poradi}</td>
              <td>{r.jmeno}</td>
              <td>{r.played}</td>
              <td>{r.wins}</td>
              <td>{r.losses}</td>
              <td>{r.sets_won}:{r.sets_lost}</td>
              <td>{r.sets_diff > 0 ? `+${r.sets_diff}` : r.sets_diff}</td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('cs-CZ', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      weekday: 'long'
    });
  };

  if (loading) {
    return (
      <div className="tournament-detail-container">
        <div className="loading-state">
          <div className="loading-spinner"></div>
          <p>Načítání turnaje...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="tournament-detail-container">
        <div className="error-state">
          <p>❌ {error}</p>
          <button onClick={() => navigate('/turnaje')} className="btn-back">
            Zpět na seznam
          </button>
        </div>
      </div>
    );
  }

  if (!tournament) {
    return null;
  }

  return (
    <div className="tournament-detail-container">
      <div className="detail-header">
        <button onClick={() => navigate('/turnaje')} className="btn-back-arrow">
          ← Zpět na seznam
        </button>
        <div className="header-content">
          <h1>{tournament.nazev}</h1>
          <span className={`status-badge status-${tournament.status}`}>
            {getStatusLabel(tournament.status)}
          </span>
        </div>
      </div>

      <div className="tabs">
        <button className={`tab ${activeTab==='prehled'?'active':''}`} onClick={()=>setActiveTab('prehled')}>Přehled</button>
        <button className={`tab ${activeTab==='hraci'?'active':''}`} onClick={()=>setActiveTab('hraci')}>Hráči</button>
        <button className={`tab ${activeTab==='zapasy'?'active':''}`} onClick={()=>{ setActiveTab('zapasy'); fetchMatches(); }}>Zápasy (skupiny)</button>
        {tournament.typ === 'smiseny' && (
          <button className={`tab ${activeTab==='playoff'?'active':''}`} onClick={()=>{ setActiveTab('playoff'); fetchMatches(); }}>Play-off</button>
        )}
        <button className={`tab ${activeTab==='tabulka'?'active':''}`} onClick={()=>{ setActiveTab('tabulka'); fetchStandings(); }}>Tabulka</button>
      </div>

      <div className="detail-content">
        {notification.message && (
          <div className={`notification notification-${notification.type}`}>
            <span className="notification-icon">
              {notification.type === 'success' && '✓'}
              {notification.type === 'error' && '✕'}
            </span>
            <span className="notification-message">{notification.message}</span>
            <button 
              className="notification-close" 
              onClick={() => setNotification({ message: '', type: '' })}
            >
              ✕
            </button>
          </div>
        )}
        {activeTab === 'prehled' && (
          <>
          <div className="info-section">
            <h2>Základní informace</h2>
            <div className="info-grid">
            <div className="info-item">
              <div className="info-icon">🏆</div>
              <div className="info-details">
                <div className="info-label">Typ turnaje</div>
                <div className="info-value">{getTypLabel(tournament.typ)}</div>
              </div>
            </div>

            <div className="info-item">
              <div className="info-icon">📅</div>
              <div className="info-details">
                <div className="info-label">Datum konání</div>
                <div className="info-value">{formatDate(tournament.datum)}</div>
              </div>
            </div>

            <div className="info-item">
              <div className="info-icon">📍</div>
              <div className="info-details">
                <div className="info-label">Místo konání</div>
                <div className="info-value">{tournament.misto}</div>
              </div>
            </div>

            <div className="info-item">
              <div className="info-icon">👥</div>
              <div className="info-details">
                <div className="info-label">Maximální počet hráčů</div>
                <div className="info-value">{tournament.maxPocetHracu} hráčů</div>
              </div>
            </div>

            <div className="info-item">
              <div className="info-icon">🧾</div>
              <div className="info-details">
                <div className="info-label">Počet stolů</div>
                <div className="info-value">{tournament.pocetStolu || 1}</div>
              </div>
            </div>
            </div>
          </div>

          {tournament.popis && (
            <div className="info-section">
              <h2>Popis turnaje</h2>
              <div className="description-box">
                <p>{tournament.popis}</p>
              </div>
            </div>
          )}

          <div className="info-section">
            <h2>Metadata</h2>
            <div className="metadata-grid">
              <div className="metadata-item">
                <span className="metadata-label">ID turnaje:</span>
                <span className="metadata-value">{tournament.id}</span>
              </div>
              <div className="metadata-item">
                <span className="metadata-label">Vytvořeno:</span>
                <span className="metadata-value">
                  {tournament.created_at ? new Date(tournament.created_at).toLocaleString('cs-CZ') : 'N/A'}
                </span>
              </div>
            </div>
          </div>

          <div className="action-buttons">
            {tournament.status === 'nadchazejici' && (
              <button className="btn-start" onClick={handleStartTournament}>
                🚀 Zahájit turnaj
              </button>
            )}
            <button className="btn-edit" onClick={() => navigate(`/turnaje/${id}/upravit`)}>
              ✏️ Upravit turnaj
            </button>
            <button className="btn-delete" onClick={() => {
              if (window.confirm('Opravdu chcete smazat tento turnaj?')) {
                fetch(`http://localhost:3000/api/tournaments/${id}`, { method: 'DELETE' })
                  .then(() => navigate('/turnaje'))
                  .catch(err => alert('Chyba při mazání'));
              }
            }}>
              🗑️ Smazat turnaj
            </button>
          </div>
          </>
        )}

        {activeTab === 'hraci' && (
          <div className="info-section">
            <div className="section-header">
              <h2>Hráči ({players.length}/{tournament.maxPocetHracu})</h2>
            </div>
            <form onSubmit={handleAddPlayer} className="add-player-form">
              <div className="form-group-inline">
                <input
                  type="text"
                  value={newPlayerName}
                  onChange={(e) => setNewPlayerName(e.target.value)}
                  placeholder="Zadejte jméno hráče"
                  className="player-input"
                  disabled={tournament.status !== 'nadchazejici'}
                />
                <button 
                  type="submit" 
                  className="btn-add-player"
                  disabled={players.length >= tournament.maxPocetHracu || tournament.status !== 'nadchazejici'}
                >
                  + Přidat hráče
                </button>
              </div>
            </form>

            {players.length === 0 ? (
              <div className="empty-players">
                <p>Zatím nejsou přidáni žádní hráči</p>
              </div>
            ) : (
              <div className="players-list">
                {players.map((player, index) => (
                  <div key={player.id} className="player-item">
                    <span className="player-number">{index + 1}</span>
                    <span className="player-name">{player.jmeno}</span>
                    {tournament.status === 'nadchazejici' && (
                      <button
                        className="btn-remove-player"
                        onClick={() => handleDeletePlayer(player.id)}
                        title="Odstranit hráče"
                      >
                        ✕
                      </button>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {activeTab === 'zapasy' && (
          <GroupMatchesSection
            tournament={tournament}
            matches={matches}
            onStartTournament={handleStartTournament}
            saveMatchResult={saveMatchResult}
            resetMatchResult={resetMatchResult}
            handleMatchStateUpdate={handleMatchStateUpdate}
            editingMatchId={editingMatchId}
            setEditingMatchId={setEditingMatchId}
            editingScore={editingScore}
            setEditingScore={setEditingScore}
            getMatchesByRound={getMatchesByRound}
            getRoundLabel={getRoundLabel}
            getStatusLabel={getStatusLabel}
            getTableOptions={getTableOptions}
          />
        )}

        {activeTab === 'playoff' && tournament.typ === 'smiseny' && (
          <PlayoffSection
            tournament={tournament}
            matches={matches}
            id={id}
            fetchMatches={fetchMatches}
            setNotification={setNotification}
            saveMatchResult={saveMatchResult}
            resetMatchResult={resetMatchResult}
            handleMatchStateUpdate={handleMatchStateUpdate}
            getTableOptions={getTableOptions}
            getPlayoffRoundName={getPlayoffRoundName}
            getStatusLabel={getStatusLabel}
            editingMatchId={editingMatchId}
            setEditingMatchId={setEditingMatchId}
            editingScore={editingScore}
            setEditingScore={setEditingScore}
          />
        )}

        {activeTab === 'tabulka' && (
          <div className="info-section">
            <h2>Tabulka</h2>
            {standings && standings.type === 'pavouk' && (
              <div className="empty-players"><p>Pořadí není dostupné pro vyřazovací systém.</p></div>
            )}
            {standings && standings.type === 'skupina' && standings.standings && standings.standings.length > 0 && (
              <div className="standings">
                {renderStandingsTable(standings.standings)}
              </div>
            )}
            {standings && standings.type === 'smiseny' && standings.groups && standings.groups.length > 0 && (
              <div className="standings">
                {standings.groups.map(g => (
                  <div key={g.group} style={{marginBottom: '1rem'}}>
                    <h3 className="round-title">Skupina {g.group}</h3>
                    {renderStandingsTable(g.standings)}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

      </div>
    </div>
  );
}

export default TournamentDetail;
